{
  "openapi": "3.1.0",
  "info": {
    "title": "Store-GG-API",
    "version": "1.0",
    "contact": {
      "name": "Dimas Pondra Oktafianto",
      "email": "dimaspondrao@gmail.com"
    },
    "description": "API Store GG"
  },
  "servers": [
    {
      "url": "http://storegg-backend.dimasoktafianto.my.id/api/v1",
      "description": "production"
    }
  ],
  "paths": {
    "/auth/signup": {
      "post": {
        "summary": "Sign Up",
        "operationId": "post-SignUp",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Success": {
                    "value": {
                      "data": {
                        "name": "Example",
                        "username": "example",
                        "email": "example@mail.com",
                        "role": "user",
                        "status": "Y",
                        "phoneNumber": "082245620000",
                        "_id": "6215abf6f45d39cf3eb6412c",
                        "createdAt": "2022-02-23T03:37:26.093Z",
                        "updatedAt": "2022-02-23T03:37:26.093Z",
                        "__v": 0
                      }
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Failed Validation": {
                    "value": {
                      "message": "Something wrong",
                      "errors": [
                        {
                          "value": "",
                          "msg": "name is required",
                          "param": "name",
                          "location": "body"
                        },
                        {
                          "value": "",
                          "msg": "name min 3 character",
                          "param": "name",
                          "location": "body"
                        },
                        {
                          "value": "",
                          "msg": "username is required",
                          "param": "username",
                          "location": "body"
                        },
                        {
                          "value": "",
                          "msg": "username min 3 character",
                          "param": "username",
                          "location": "body"
                        },
                        {
                          "value": "",
                          "msg": "email is required",
                          "param": "email",
                          "location": "body"
                        },
                        {
                          "value": "",
                          "msg": "Not an email",
                          "param": "email",
                          "location": "body"
                        },
                        {
                          "value": "",
                          "msg": "password is required",
                          "param": "password",
                          "location": "body"
                        },
                        {
                          "value": "",
                          "msg": "password min 6 character",
                          "param": "password",
                          "location": "body"
                        },
                        {
                          "value": "",
                          "msg": "phone number is required",
                          "param": "phoneNumber",
                          "location": "body"
                        },
                        {
                          "value": "",
                          "msg": "phone number min 9 character",
                          "param": "phoneNumber",
                          "location": "body"
                        },
                        {
                          "value": "",
                          "msg": "is not indonesian phone number",
                          "param": "phoneNumber",
                          "location": "body"
                        }
                      ]
                    }
                  },
                  "Failed When Duplicate Email": {
                    "value": {
                      "message": "email is registered"
                    }
                  }
                }
              }
            }
          }
        },
        "tags": [
          "Authentication"
        ],
        "description": "Endpoint sign up player account",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application-json"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "username": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "phoneNumber": {
                    "type": "string"
                  },
                  "avatar": {
                    "type": "object"
                  }
                },
                "required": [
                  "name",
                  "username",
                  "email",
                  "password",
                  "phoneNumber"
                ]
              }
            }
          }
        }
      },
      "parameters": []
    },
    "/auth/signin": {
      "post": {
        "summary": "Sign In",
        "operationId": "post-auth-signin",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Success": {
                    "value": {
                      "data": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXIiOnsiaWQiOiI2MjE0NmIyODgyYzZmZTMwYjQzZDAzNjciLCJuYW1lIjoiRGltYXMgUG9uZHJhIE9rdGFmaWFudG8iLCJ1c2VybmFtZSI6ImRpbWFzcG9uZHJhIiwiZW1haWwiOiJkaW1hc0BnbWFpbC5jb20ifSwiaWF0IjoxNjQ1NTg3MjIxfQ"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Failed": {
                    "value": {
                      "message": "email or password is wrong"
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Endpoint sign in player account",
        "tags": [
          "Authentication"
        ],
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "required": [
                  "email",
                  "password"
                ]
              },
              "examples": {
                "Example": {
                  "value": {
                    "email": "example@mail.com",
                    "password": "example"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/players/landing-page": {
      "get": {
        "summary": "Landing Page - All Vouchers",
        "tags": [
          "Player"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Success": {
                    "value": {
                      "data": [
                        {
                          "_id": "603152e0a4dd027eefadde64",
                          "name": "Valorant",
                          "category": {
                            "_id": "603152e0a4dd027eefacce62",
                            "name": "Desktop",
                            "__v": 0
                          },
                          "status": "Y",
                          "thumbnail": "4ad0887ea26a9ddf942003a11fb70d3f.png"
                        },
                        {
                          "_id": "603152e0a4dd027eefadde61",
                          "name": "Call of Duty: Modern",
                          "category": {
                            "_id": "603152e0a4dd027eefacce61",
                            "name": "PC",
                            "__v": 0
                          },
                          "status": "Y",
                          "thumbnail": "c199520527cb792a75db3671ea581bc9.png"
                        },
                        {
                          "_id": "603152e0a4dd027eefadde62",
                          "name": "Mobile Legends",
                          "category": {
                            "_id": "603152e0a4dd027eefacce62",
                            "name": "Desktop",
                            "__v": 0
                          },
                          "status": "Y",
                          "thumbnail": "926a505d19a5736cdedd8a252a6dd210.png"
                        },
                        {
                          "_id": "603152e0a4dd027eefadde63",
                          "name": "Clash of Clans",
                          "category": {
                            "_id": "603152e0a4dd027eefacce62",
                            "name": "Desktop",
                            "__v": 0
                          },
                          "status": "Y",
                          "thumbnail": "da9b09c0015e53c8bb8b3e693609b9d5.png"
                        },
                        {
                          "_id": "603152e0a4dd027eefadde60",
                          "name": "Super Mechs",
                          "category": {
                            "_id": "603152e0a4dd027eefacce60",
                            "name": "Mobile",
                            "__v": 0
                          },
                          "status": "Y",
                          "thumbnail": "e6c11f39ed84e84057194706c62b292c.png"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-players-landing-page",
        "description": "Endpoint landing page (all vouchers)",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          }
        ]
      }
    },
    "/players/{id}/detail": {
      "parameters": [
        {
          "schema": {
            "type": "string",
            "example": "603152e0a4dd027eefadde61"
          },
          "name": "id",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Detail Voucher",
        "tags": [
          "Player"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Success": {
                    "value": {
                      "data": {
                        "_id": "603152e0a4dd027eefadde61",
                        "name": "Call of Duty: Modern",
                        "category": {
                          "_id": "603152e0a4dd027eefacce61",
                          "name": "PC",
                          "__v": 0
                        },
                        "isFeatured": true,
                        "status": "Y",
                        "thumbnail": "c199520527cb792a75db3671ea581bc9.png",
                        "user": {
                          "_id": "60acf086e2e33c145dff9e65",
                          "phoneNumber": "08154023799",
                          "name": "admin bwa"
                        },
                        "nominals": [
                          {
                            "_id": "60bebe1c3c9c29aa8d6ad445",
                            "coinQuantity": 50,
                            "price": 75000,
                            "coinName": "Jewel",
                            "createdAt": "2021-06-08T00:47:24.737Z",
                            "updatedAt": "2021-06-08T00:47:24.737Z",
                            "__v": 0
                          },
                          {
                            "_id": "60bebe333c9c29aa8d6ad446",
                            "coinQuantity": 100,
                            "price": 125000,
                            "coinName": "Jewel",
                            "createdAt": "2021-06-08T00:47:47.143Z",
                            "updatedAt": "2021-06-08T00:47:47.143Z",
                            "__v": 0
                          },
                          {
                            "_id": "60bebf303c9c29aa8d6ad447",
                            "coinQuantity": 150,
                            "price": 150000,
                            "coinName": "Jewel",
                            "createdAt": "2021-06-08T00:52:00.699Z",
                            "updatedAt": "2021-06-08T00:52:00.699Z",
                            "__v": 0
                          },
                          {
                            "_id": "60bebf503c9c29aa8d6ad448",
                            "coinQuantity": 225,
                            "price": 175000,
                            "coinName": "Jewel",
                            "createdAt": "2021-06-08T00:52:32.921Z",
                            "updatedAt": "2021-06-08T00:55:14.822Z",
                            "__v": 0
                          },
                          {
                            "_id": "60bebf5c3c9c29aa8d6ad449",
                            "coinQuantity": 500,
                            "price": 325000,
                            "coinName": "Jewel",
                            "createdAt": "2021-06-08T00:52:44.241Z",
                            "updatedAt": "2021-06-08T00:52:44.241Z",
                            "__v": 0
                          }
                        ],
                        "__v": 0,
                        "updatedAt": "2022-02-12T00:03:22.917Z"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-players-id-detail",
        "description": "Endpoint detail voucher by id",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          }
        ]
      }
    },
    "/players/categories": {
      "get": {
        "summary": "Categories",
        "tags": [
          "Player"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Success": {
                    "value": {
                      "data": [
                        {
                          "_id": "603152e0a4dd027eefacce62",
                          "name": "Desktop"
                        },
                        {
                          "_id": "603152e0a4dd027eefacce60",
                          "name": "Mobile"
                        },
                        {
                          "_id": "603152e0a4dd027eefacce61",
                          "name": "PC"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-players-categories",
        "description": "Endpoint all categories",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          }
        ]
      }
    },
    "/players/checkout": {
      "post": {
        "summary": "Checkout",
        "operationId": "post-players-checkout",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Success": {
                    "value": {
                      "message": "successfully checkout item."
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Not authorized": {
                    "value": {
                      "error": "Not authorized to access this resource"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Failed Validation": {
                    "value": {
                      "message": "Something wrong",
                      "errors": [
                        {
                          "value": "",
                          "msg": "name is required",
                          "param": "name",
                          "location": "body"
                        },
                        {
                          "value": "",
                          "msg": "name min 3 character",
                          "param": "name",
                          "location": "body"
                        },
                        {
                          "value": "",
                          "msg": "account user is required",
                          "param": "accountUser",
                          "location": "body"
                        },
                        {
                          "value": "",
                          "msg": "account user min 3 character",
                          "param": "accountUser",
                          "location": "body"
                        },
                        {
                          "value": "",
                          "msg": "nominal is required",
                          "param": "nominal",
                          "location": "body"
                        },
                        {
                          "value": "",
                          "msg": "voucher is required",
                          "param": "voucher",
                          "location": "body"
                        },
                        {
                          "value": "",
                          "msg": "payment is required",
                          "param": "payment",
                          "location": "body"
                        },
                        {
                          "value": "",
                          "msg": "bank is required",
                          "param": "bank",
                          "location": "body"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Endpoint checkout ",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "example": "Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXIiOnsiaWQiOiI2MjE0NmIyODgyYzZmZT"
            },
            "in": "header",
            "name": "Authorization",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "accountUser": {
                    "type": "string",
                    "description": "min 3 characters"
                  },
                  "name": {
                    "type": "string",
                    "description": "min 3 characters"
                  },
                  "nominal": {
                    "type": "string"
                  },
                  "voucher": {
                    "type": "string"
                  },
                  "payment": {
                    "type": "string"
                  },
                  "bank": {
                    "type": "string"
                  }
                },
                "required": [
                  "accountUser",
                  "name",
                  "nominal",
                  "voucher",
                  "payment",
                  "bank"
                ]
              },
              "examples": {
                "example-1": {
                  "value": {
                    "accountUser": "string",
                    "name": "string",
                    "nominal": "string",
                    "voucher": "string",
                    "payment": "string",
                    "bank": "string"
                  }
                }
              }
            }
          }
        },
        "tags": [
          "Player"
        ]
      }
    },
    "/players/history": {
      "get": {
        "summary": "Checkout History",
        "tags": [
          "Player"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Success": {
                    "value": {
                      "data": [
                        {
                          "historyVoucherTopup": {
                            "gameName": "Valorant",
                            "category": "Desktop",
                            "thumbnail": "4ad0887ea26a9ddf942003a11fb70d3f.png",
                            "coinName": "GOLD",
                            "coinQuantity": "225",
                            "price": 4250000
                          },
                          "historyPayment": {
                            "type": "Tranfer",
                            "bankName": "BCA",
                            "name": "ADMIN BWA 1",
                            "accountNumber": "123456789"
                          },
                          "historyUser": {
                            "name": "admin bwa",
                            "phoneNumber": 8154023799
                          },
                          "_id": "62147d801e3fa94e9cd042c7",
                          "name": "Dimas Pondra Oktafianto",
                          "accountUser": "78991",
                          "tax": 425000,
                          "value": 4675000,
                          "status": "pending",
                          "user": "60acf086e2e33c145dff9e65",
                          "category": "603152e0a4dd027eefacce62",
                          "voucherTopup": "603152e0a4dd027eefadde64",
                          "player": "62146b2882c6fe30b43d0367",
                          "createdAt": "2022-02-22T06:06:56.332Z",
                          "updatedAt": "2022-02-22T06:06:56.332Z",
                          "__v": 0
                        },
                        {
                          "historyVoucherTopup": {
                            "gameName": "Valorant",
                            "category": "Desktop",
                            "thumbnail": "4ad0887ea26a9ddf942003a11fb70d3f.png",
                            "coinName": "GOLD",
                            "coinQuantity": "225",
                            "price": 4250000
                          },
                          "historyPayment": {
                            "type": "Tranfer",
                            "bankName": "BCA",
                            "name": "ADMIN BWA 1",
                            "accountNumber": "123456789"
                          },
                          "historyUser": {
                            "name": "admin bwa",
                            "phoneNumber": 8154023799
                          },
                          "_id": "6215b24cf45d39cf3eb6413e",
                          "name": "Dimas Pondra Oktafianto",
                          "accountUser": "78991",
                          "tax": 425000,
                          "value": 4675000,
                          "status": "pending",
                          "user": "60acf086e2e33c145dff9e65",
                          "category": "603152e0a4dd027eefacce62",
                          "voucherTopup": "603152e0a4dd027eefadde64",
                          "player": "62146b2882c6fe30b43d0367",
                          "createdAt": "2022-02-23T04:04:28.864Z",
                          "updatedAt": "2022-02-23T04:04:28.864Z",
                          "__v": 0
                        }
                      ],
                      "total": 9350000
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Not authorized": {
                    "value": {
                      "error": "Not authorized to access this resource"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-players-history",
        "description": "Endpoint checkout history player",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "example": "Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXIiOnsiaWQiOiI2MjE0NmIyODgyYzZmZT"
            },
            "in": "header",
            "name": "Authorization",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "example": "pending",
              "enum": [
                "pending",
                "success",
                "failed"
              ]
            },
            "in": "query",
            "name": "Status"
          }
        ]
      },
      "parameters": []
    },
    "/players/history/{id}/detail": {
      "parameters": [
        {
          "schema": {
            "type": "string",
            "example": "620391e5af1f63b00e433649"
          },
          "name": "id",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Detail Checkout History",
        "tags": [
          "Player"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Success": {
                    "value": {
                      "data": {
                        "historyVoucherTopup": {
                          "gameName": "Valorant",
                          "category": "Desktop",
                          "thumbnail": "4ad0887ea26a9ddf942003a11fb70d3f.png",
                          "coinName": "GOLD",
                          "coinQuantity": "225",
                          "price": 4250000
                        },
                        "historyPayment": {
                          "type": "Tranfer",
                          "bankName": "BCA",
                          "name": "ADMIN BWA 1",
                          "accountNumber": "123456789"
                        },
                        "historyUser": {
                          "name": "admin bwa",
                          "phoneNumber": 8154023799
                        },
                        "_id": "62147d801e3fa94e9cd042c7",
                        "name": "Dimas Pondra Oktafianto",
                        "accountUser": "78991",
                        "tax": 425000,
                        "value": 4675000,
                        "status": "pending",
                        "user": "60acf086e2e33c145dff9e65",
                        "category": "603152e0a4dd027eefacce62",
                        "voucherTopup": "603152e0a4dd027eefadde64",
                        "player": "62146b2882c6fe30b43d0367",
                        "createdAt": "2022-02-22T06:06:56.332Z",
                        "updatedAt": "2022-02-22T06:06:56.332Z",
                        "__v": 0
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Not authorized": {
                    "value": {
                      "error": "Not authorized to access this resource"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Not Found": {
                    "value": {
                      "message": "history not found"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-players-history-id-detail",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "example": "Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXIiOnsiaWQiOiI2MjE0NmIyODgyYzZmZT"
            },
            "in": "header",
            "name": "Authorization",
            "required": true
          }
        ],
        "description": "Endpoint detail checkout history player"
      }
    },
    "/players/dashboard": {
      "get": {
        "summary": "Dashboard Player",
        "tags": [
          "Player"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Success": {
                    "value": {
                      "data": [
                        {
                          "historyVoucherTopup": {
                            "gameName": "Valorant",
                            "category": "Desktop",
                            "thumbnail": "4ad0887ea26a9ddf942003a11fb70d3f.png",
                            "coinName": "GOLD",
                            "coinQuantity": "225",
                            "price": 4250000
                          },
                          "historyPayment": {
                            "type": "Tranfer",
                            "bankName": "BCA",
                            "name": "ADMIN BWA 1",
                            "accountNumber": "123456789"
                          },
                          "historyUser": {
                            "name": "admin bwa",
                            "phoneNumber": 8154023799
                          },
                          "_id": "6215b24cf45d39cf3eb6413e",
                          "name": "Dimas Pondra Oktafianto",
                          "accountUser": "78991",
                          "tax": 425000,
                          "value": 4675000,
                          "status": "pending",
                          "user": "60acf086e2e33c145dff9e65",
                          "category": {
                            "_id": "603152e0a4dd027eefacce62",
                            "name": "Desktop",
                            "__v": 0
                          },
                          "voucherTopup": "603152e0a4dd027eefadde64",
                          "player": "62146b2882c6fe30b43d0367",
                          "createdAt": "2022-02-23T04:04:28.864Z",
                          "updatedAt": "2022-02-23T04:04:28.864Z",
                          "__v": 0
                        },
                        {
                          "historyVoucherTopup": {
                            "gameName": "Valorant",
                            "category": "Desktop",
                            "thumbnail": "4ad0887ea26a9ddf942003a11fb70d3f.png",
                            "coinName": "GOLD",
                            "coinQuantity": "225",
                            "price": 4250000
                          },
                          "historyPayment": {
                            "type": "Tranfer",
                            "bankName": "BCA",
                            "name": "ADMIN BWA 1",
                            "accountNumber": "123456789"
                          },
                          "historyUser": {
                            "name": "admin bwa",
                            "phoneNumber": 8154023799
                          },
                          "_id": "62147d801e3fa94e9cd042c7",
                          "name": "Dimas Pondra Oktafianto",
                          "accountUser": "78991",
                          "tax": 425000,
                          "value": 4675000,
                          "status": "pending",
                          "user": "60acf086e2e33c145dff9e65",
                          "category": {
                            "_id": "603152e0a4dd027eefacce62",
                            "name": "Desktop",
                            "__v": 0
                          },
                          "voucherTopup": "603152e0a4dd027eefadde64",
                          "player": "62146b2882c6fe30b43d0367",
                          "createdAt": "2022-02-22T06:06:56.332Z",
                          "updatedAt": "2022-02-22T06:06:56.332Z",
                          "__v": 0
                        }
                      ],
                      "count": [
                        {
                          "_id": "603152e0a4dd027eefacce62",
                          "value": 9350000,
                          "name": "Desktop"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Not authorized": {
                    "value": {
                      "error": "Not authorized to access this resource"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-players-dashboard",
        "description": "Endpoint dashboard player",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "example": "Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXIiOnsiaWQiOiI2MjE0NmIyODgyYzZmZT"
            },
            "in": "header",
            "name": "Authorization",
            "required": true
          }
        ]
      }
    },
    "/players/profile": {
      "get": {
        "summary": "Profile Player",
        "tags": [
          "Player"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Success": {
                    "value": {
                      "data": {
                        "id": "62146b2882c6fe30b43d0367",
                        "name": "Example",
                        "username": "example",
                        "email": "example@mail.com",
                        "phone_number": "082245620000"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Not authorized": {
                    "value": {
                      "error": "Not authorized to access this resource"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-players-profile",
        "description": "Endpoint profile player",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "example": "Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXIiOnsiaWQiOiI2MjE0NmIyODgyYzZmZT"
            },
            "in": "header",
            "name": "Authorization",
            "required": true
          }
        ]
      },
      "put": {
        "summary": "Edit Profile Player",
        "operationId": "put-players-profile",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Success": {
                    "value": {
                      "data": {
                        "id": "62146b2882c6fe30b43d0367",
                        "name": "Example",
                        "phoneNumber": "082245620000"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Not authorized": {
                    "value": {
                      "error": "Not authorized to access this resource"
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Endpoint edit profile player",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "example": "Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXIiOnsiaWQiOiI2MjE0NmIyODgyYzZmZT"
            },
            "in": "header",
            "name": "Authorization",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "phoneNumber": {
                    "type": "string"
                  },
                  "avatar": {
                    "type": "object"
                  }
                }
              },
              "examples": {
                "example-1": {
                  "value": {
                    "name": "string",
                    "phoneNumber": "string",
                    "avatar": {}
                  }
                }
              }
            }
          }
        },
        "tags": [
          "Player"
        ]
      }
    }
  },
  "components": {
    "schemas": {}
  },
  "tags": [
    {
      "name": "Authentication"
    },
    {
      "name": "Player"
    }
  ]
}